package gk.myname.vn.admin;
// Generated Jul 16, 2011 10:32:42 PM by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;
import org.apache.log4j.Logger;

/**
 * LogAccess generated by hbm2java
 */
public class LogAccess implements java.io.Serializable {

    public Logger logger = Logger.getLogger(LogAccess.class);
    private long id;
    private String resourceAccess;
    private String fromIp;
    private Timestamp timeAccess;

    public LogAccess() {
    }

    public LogAccess(long id) {
        this.id = id;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getResourceAccess() {
        return this.resourceAccess;
    }

    public void setResourceAccess(String resourceAccess) {
        this.resourceAccess = resourceAccess;
    }

    public String getFromIp() {
        return this.fromIp;
    }

    public void setFromIp(String fromIp) {
        this.fromIp = fromIp;
    }

    public Timestamp getTimeAccess() {
        return this.timeAccess;
    }

    public void setTimeAccess(Timestamp timeAccess) {
        this.timeAccess = timeAccess;
    }
}
